/* target cpu dependent options file */
/* automatically generated -- DO NOT EDIT!! */

#ifndef __CPU_OPTIONS_h
#define __CPU_OPTIONS_h
#if 0
/* lib-rtos/core/include/core/cpuopts.h.  Generated by Delta IDE.  */
/* lib-rtos/core/include/core/cpuopts-tmp.h.in.  Generated by Delta IDE.  */

/* if multiprocessing is enabled */
#define RTOS_MULTIPROCESSING 1

/* if using newlib */
#define RTOS_NEWLIB 1

/* if posix api is supported */
#define RTOS_POSIX_API 1

/* if vxworks api is supported */
/* #undef RTOS_VXWORKS_API */

/* RTOS version string */
#define RTEMS_VERSION "4.11"

/* if using inlines */
#define USE_INLINES 1
#endif

/* if multiprocessing is enabled */
#define RTEMS_MULTIPROCESSING 1

/* if using newlib */
#define RTEMS_NEWLIB 1

/* if posix api is supported */
#define RTEMS_POSIX_API 1

/* RTEMS version string */
#define RTEMS_VERSION "4.11"

/* if using inlines */
#define USE_INLINES 1

#define __BSD_VISIBLE 1

#define _KERNEL 1


#endif
